#!/usr/bin/env bash

_delete() {
    [ -d ".test_tmp" ] && rm -r ".test_tmp";
    [ -f ".test_tmp_application-pgp-keys.svg" ] && rm ".test_tmp_application-pgp-keys.svg";
    return 0;
};

_create() {

    mkdir -p ".test_tmp/dir1/dir2";
    touch ".test_tmp_application-pgp-keys.svg";
    touch ".test_tmp/battery-050-charging.svg";
    touch ".test_tmp/dir1/audio-x-mpeg.svg";
    touch ".test_tmp/dir1/dir2/terminal.svg";
    ln -sr ".test_tmp/dir1/dir2/terminal.svg" ".test_tmp/dir1/dir2/terminal-link.svg";

    cat <<EOM > ".test_tmp_application-pgp-keys.svg"
<svg fill="#4caf50" height="48" viewBox="0 0 48 48" width="48" xmlns="http://www.w3.org/2000/svg"><path d="m12 6c-.93 0-1.760547.429844-2.310547 1.089844l-2.769531 3.359375c-.58.7-.919922 1.580781-.919922 2.550781v25c0 2.21 1.79 4 4 4h28c2.21 0 4-1.79 4-4v-25c0-.97-.340156-1.850781-.910156-2.550781l-2.769532-3.359375c-.56-.66-1.390312-1.089844-2.320312-1.089844zm12 10.5c2.76 0 5 2.239999 5 5v2h1c1.105 0 2 .895 2 2v10c0 1.105-.895 2-2 2h-12c-1.105 0-2-.895-2-2v-10c0-1.105.895-2 2-2h1v-2c0-2.760001 2.24-5 5-5z" fill="#4caf50"/><path d="m10.25 10 1.63-2h24l1.87 2z" fill="#fff"/><g fill="#4caf50"><path d="m24 32.5c-1.105 0-2-.894999-2-2 0-1.104999.895-2 2-2s2 .895001 2 2c0 1.105001-.895 2-2 2z"/><path d="m27.1 23.500001h-6.2v-2c0-1.71 1.39-3.1 3.1-3.1s3.1 1.39 3.1 3.1z"/></g></svg>
EOM
    cat <<EOM > ".test_tmp/dir1/audio-x-mpeg.svg"
<svg fill="#4caf50" height="48" viewBox="0 0 48 48" width="48" xmlns="http://www.w3.org/2000/svg"><path d="M28.93 27L22 40V29h-4l1.07-2H14v14.33C14 42.8 15.19 44 16.67 44h14.67c1.47 0 2.67-1.19 2.67-2.67V27h-5.08z" fill="#4caf50"/><path d="M31.33 8H28V4h-8v4h-3.33C15.19 8 14 9.19 14 10.67V27h5.07L26 14v11h4l-1.07 2H34V10.67C34 9.19 32.81 8 31.33 8z" fill-opacity=".3" fill="#4caf50"/></svg>
EOM
    cat <<EOM > ".test_tmp/battery-050-charging.svg"
<svg fill="#4caf50" height="48" viewBox="0 0 48 48" width="48" xmlns="http://www.w3.org/2000/svg"><path d="M28.93 27L22 40V29h-4l1.07-2H14v14.33C14 42.8 15.19 44 16.67 44h14.67c1.47 0 2.67-1.19 2.67-2.67V27h-5.08z" fill="#4caf50"/><path d="M31.33 8H28V4h-8v4h-3.33C15.19 8 14 9.19 14 10.67V27h5.07L26 14v11h4l-1.07 2H34V10.67C34 9.19 32.81 8 31.33 8z" fill-opacity=".3" fill="#4caf50"/></svg>
EOM
    cat <<EOM > ".test_tmp/dir1/dir2/terminal.svg"
<svg fill="#4caf50" viewBox="0 0 48 48" xmlns="http://www.w3.org/2000/svg">
	<rect fill="#4caf50" height="36" rx="4" width="40" x="4" y="6"/>
	<path d="m8 10h32v28h-32z" fill="#000"/>
	<text style="font-family:Inconsolata;font-size:20;font-weight:bold;letter-spacing:0;word-spacing:0;fill:#4caf50" x="11.26" y="25.64">
		<tspan fill="#4caf50" x="11.26" y="25.64">&gt;_</tspan>
	</text>
</svg>
EOM
};

_gotest() {
    go test "./globber";
    go test "./futil";
    go test "./replacer";
};

_cmdtest() {

    go run main.go -eq -c 1000 -o '(fill="#)[a-zA-Z0-9]{6}(")' -n '${1}0000ff${2}' ".test_tmp_application-pgp-keys.svg" ".test_tmp/dir1/audio-x-mpeg.svg";

    ! _md5chk ".test_tmp_application-pgp-keys.svg" "d90b61134d161e3c3ad86baddce0a7c7" && return 1;
    ! _md5chk ".test_tmp/dir1/audio-x-mpeg.svg" "1c11eae4ebb4a6564ae07845fe4f6c84" && return 1;

    go run main.go -req -c 1000 -o '(fill="#)[a-zA-Z0-9]{6}(")' -n '${1}ff0000${2}' -i '*.svg' ".test_tmp";

    ! _md5chk ".test_tmp/battery-050-charging.svg" "0525e4fbe72fc2c3e2edf930dcb1d663" && return 1;
    ! _md5chk ".test_tmp/dir1/dir2/terminal.svg" "3e2365963bb2a9da8adbb5bec679c63c" && return 1;
};

_md5sum() {
    local -r f="${1}";
    local sum;
    sum="$(md5sum "${f}")";
    sum="${sum%  *}";
    echo "${sum}";
};

_md5chk() {
    local -r f="${1}";
    local -r expected="${2}";
    local got;
    got="$(_md5sum "${f}")";

    if [ "${got}" != "${expected}" ]; then
        echo "md5sum check for '${f}' did not pass";
        return 1;
    else
        return 0;
    fi;
};

_delete;
_create;
_gotest;
_cmdtest;
_delete;
