#!/usr/bin/env bash

_populate() {
    mkdir -p ".test_tmp/dir1/dir2";
    touch ".test_tmp_file.svg";
    touch ".test_tmp/battery-050-charging.svg";
    touch ".test_tmp/dir1/file1.svg";
    touch ".test_tmp/dir1/dir2/file2.svg";
    ln -sr ".test_tmp/dir1/dir2/file2.svg" ".test_tmp/dir1/dir2/file2-link.svg";
    echo '<svg fill="#4caf50" height="48" viewBox="0 0 48 48" width="48" xmlns="http://www.w3.org/2000/svg"><path d="M28.93 27L22 40V29h-4l1.07-2H14v14.33C14 42.8 15.19 44 16.67 44h14.67c1.47 0 2.67-1.19 2.67-2.67V27h-5.08z" fill="#4caf50"/><path d="M31.33 8H28V4h-8v4h-3.33C15.19 8 14 9.19 14 10.67V27h5.07L26 14v11h4l-1.07 2H34V10.67C34 9.19 32.81 8 31.33 8z" fill-opacity=".3" fill="#4caf50"/></svg>' > ".test_tmp/battery-050-charging.svg";
};

_test() {
    go test "./futil";
    go test "./replacer";
};

_cleanup() {
    [ -d ".test_tmp" ] && rm -r ".test_tmp";
    [ -d ".test_tmp_file.svg" ] && rm ".test_tmp_file.svg";
};

_cleanup;
_populate;
_test;
_cleanup;
