#!/usr/bin/env bash

_delete() {
    [ -d ".test_tmp" ] && rm -r ".test_tmp";
    [ -f ".test_tmp_file.svg" ] && rm ".test_tmp_file.svg";
    return 0;
};

_create() {

    mkdir -p ".test_tmp/dir1/dir2";
    touch ".test_tmp_file.svg";
    touch ".test_tmp/battery-050-charging.svg";
    touch ".test_tmp/dir1/file1.svg";
    touch ".test_tmp/dir1/dir2/file2.svg";
    touch ".test_tmp/dir1/dir2/terminal.svg";
    ln -sr ".test_tmp/dir1/dir2/file2.svg" ".test_tmp/dir1/dir2/file2-link.svg";

    cat <<EOM > ".test_tmp/battery-050-charging.svg"
<svg fill="#4caf50" height="48" viewBox="0 0 48 48" width="48" xmlns="http://www.w3.org/2000/svg"><path d="M28.93 27L22 40V29h-4l1.07-2H14v14.33C14 42.8 15.19 44 16.67 44h14.67c1.47 0 2.67-1.19 2.67-2.67V27h-5.08z" fill="#4caf50"/><path d="M31.33 8H28V4h-8v4h-3.33C15.19 8 14 9.19 14 10.67V27h5.07L26 14v11h4l-1.07 2H34V10.67C34 9.19 32.81 8 31.33 8z" fill-opacity=".3" fill="#4caf50"/></svg>
EOM
    cat <<EOM > ".test_tmp/dir1/dir2/terminal.svg"
<svg fill="#4caf50" viewBox="0 0 48 48" xmlns="http://www.w3.org/2000/svg">
	<rect fill="#4caf50" height="36" rx="4" width="40" x="4" y="6"/>
	<path d="m8 10h32v28h-32z" fill="#000"/>
	<text style="font-family:Inconsolata;font-size:20;font-weight:bold;letter-spacing:0;word-spacing:0;fill:#4caf50" x="11.26" y="25.64">
		<tspan fill="#4caf50" x="11.26" y="25.64">&gt;_</tspan>
	</text>
</svg>
EOM
};

_gotest() {
    go test "./futil";
    go test "./replacer";
};

_cmdtest() {

    go run main.go -req -o '(fill="#)[a-zA-Z0-9]{6}(")' -n '${1}ff0000${2}' -i '*.svg' ".test_tmp";

    ! _md5chk ".test_tmp/battery-050-charging.svg" "0525e4fbe72fc2c3e2edf930dcb1d663" && return 1;
    ! _md5chk ".test_tmp/dir1/dir2/terminal.svg" "3e2365963bb2a9da8adbb5bec679c63c" && return 1;
};

_md5sum() {
    local -r f="${1}";
    local sum;
    sum="$(md5sum "${f}")";
    sum="${sum%  *}";
    echo "${sum}";
};

_md5chk() {
    local -r f="${1}";
    local -r expected="${2}";
    local got;
    got="$(_md5sum "${f}")";

    if [ "${got}" != "${expected}" ]; then
        echo "md5sum check for '${f}' did not pass";
        return 1;
    else
        return 0;
    fi;
};

_delete;
_create;
_gotest;
_cmdtest;
_delete;
